-- SENTENCIAS DDL
-- CREATE TABLE
CREATE TABLE alumno(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nro_documento VARCHAR(20) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(100)
);

-- ALTERAR UNA TABLA
ALTER TABLE alumno
ADD COLUMN nota INT DEFAULT 0;

-- ELIMINAR UNA TABLA
DROP TABLE alumno;

CREATE TABLE empresa(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    ruc VARCHAR(12) NOT NULL UNIQUE,
    razon_social VARCHAR(255) NOT NULL,
    direccion TEXT
);